version: '3'
services:
  web:
    build: .
    image: web_umenia
    ports:
      - 8080:80
    volumes:
      - .:/var/www
      - ./public:/var/www/html
      - ./vhost.conf:/etc/apache2/sites-available/000-default.conf
    links:
      - mysql
      - elasticsearch
    depends_on:
      - mysql
      - elasticsearch
    env_file: .env
    # 'web' service can speak to mysql and elasticsearch services
    # at these network addresses:
    #  - http://mysql:3306
    #  - http://elasticsearch:9200 
    # so we override the standard environment variables here:
    environment:
      DB_HOST: mysql
      ES_HOST: elasticsearch

  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch2
    image: elasticsearch
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      http.host: "0.0.0.0"
      transport.host: "127.0.0.1"
      xpack.security.enabled: "false"
      VERSION: 2.4.1
      ES_HEAP_SIZE: 8g
      MAX_MAP_COUNT: 262144
    ports:
      - "9200:9200"